### ISSUE TITLE
홈페이지에 포함되어 있는 수업 시간표 2018년도 것으로 업데이트

### ISSUE THREAD

**Issue by spostman** [KAIST-GSIS-Homepage/GSIS-homepage#1]
Update http://gsis.kaist.ac.kr/sub0203

**Comment by jiseongnoh** [comment]
이번 주말에 업데이트 하도록 하겠습니다.

**Comment by spostman** [comment]
제가 업데이트 하면 메일이 받도록 세팅해주세요. 오른쪽에 Notifications에서 turn-on하시면 될 것 같은데요

**Comment by jiseongnoh** [comment]
예, Notifications의 subscribe 버튼 눌러 확인하였습니다. 감사합니다.

**Comment by jiseongnoh** [comment]
시간표 초안 업데이트 하였습니다. 월요일 10:30부터 11:00까지는 차상길교수님의 정보보호실습과 김용대교수님의 정보보호특강 <암호공학> 수업이 겹치는 이슈가 있습니다.

**Comment by spostman** [comment]
(변경될 수 있음) 을 다음과 같이 수정해 주세요.

(대학원 상황에 따라 교과목 추가및 시간 변동이 있을 수 있습니다.)

**Comment by jiseongnoh** [comment]
예 말씀하신 대로 수정하였습니다.
