### ISSUE TITLE
GSIS 게시판에 최근에 올라온 홍보 게시글 영문판에 반영

### ISSUE THREAD

**Issue by spostman** [KAIST-GSIS-Homepage/GSIS-homepage#4]
메시지 보시고 작업 시작하시면 ACK 커맨트 남겨주세요.

**Comment by mickan921** [comment]
작업 시작했습니다.
일부 신문 스크랩 포스트와 채용 공고등의 글은 제외하고
중요한 포스트를 골라서 업로드 하겠습니다.

"장대희 박사과정, 사이버공격방어대회 논문 대상 수상" 포스트는 번역 완료했고

"[언론보도] 세계 3대 암호학회 ‘Asiacrypt 2020’ 한국에서 열린다"와
"[언론 보도] KAIST·국보연 논문 3편, 세계 유수 보안학회 ACM CCS 채택 ‘경사’"를 내일 중으로 번역 후 업데이트 할 예정입니다.

**Comment by mickan921** [comment]
완료했습니다.

**Comment by spostman** [comment]
감사합니다. 이것을 중간 정렬로 하지말고 그냥 왼쪽 정렬로 되게 보일수 없나요?

**Comment by mickan921** [comment]
관리자 인터페이스 상으론 왼쪽 정렬로 설정되어있는데 막상 접속하면 중간 정렬로 보입니다.
일반적인 방법으론 변경 불가능 할것 같으니 이미지 파일로 캡처해서 올릴까요...?

**Comment by spostman** [comment]
이거 홈페이지 버그네요.. 어쩔수 없지요. 일단은 현재 그상태로 놓아주세요

2017-12-24 17:36 GMT+09:00 Jungsuk Oh <notifications@github.com>:
